ASP.NetCore/Lab/07.StateMgt/Starter/GreatWorld/Models/Trip.cs
using System.ComponentModel.DataAnnotations;

namespace GreatWorld.Models
{
    public class Trip
    {
        [Key]
        public int id { get; set; }

        [Display(Name = "Trip Name")]
        public string? Name { get; set; }

        [DataType(DataType.Date),
          DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy}",
                      ApplyFormatInEditMode = false)]
        [Display(Name = "Created On")]
        public DateTime Created { get; set; }

        public string? UserName { get; set; }

        [Display(Name = "Full Name")]
        [RegularExpression("^([a-zA-Z]+\\s[a-zA-Z]+)$",
              ErrorMessage =
            "Full Name must be two words with a space between first and last name")]
        public string? FullName { get; set; }

        public ICollection<Stop>? Stops { get; set; }
    }
}

ASP.NetCore/Lab/07.StateMgt/Starter/GreatWorld/Controllers/API/TripController.cs
using GreatWorld.Repository;
using GreatWorld.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using AutoMapper;
using GreatWorld.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace GreatWorld.Controllers.API
{
    [Route("/api/trips")]
    [ApiController]
    public class TripController : ControllerBase
    {
        private IGreatWorldRepository _repository;
        private IMapper _mapper;

        public TripController(IGreatWorldRepository repository,
                                    IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }


        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        [HttpGet("/api/trips/{TripName?}")]
        //[HttpGet("/api/Trips.{format}"), FormatFilter]
        public IActionResult Get(string? TripName)
        {
            if (TripName != null)
            {
                //var results = _repository.GetTripByName(TripName);
                Trip results = _repository.GetUserTripByName(User.Identity.Name, TripName); ;
                return Ok(results);
            }
            //var results1 = _mapper.Map<IEnumerable<TripViewModel>>(_repository.GetAllTripsWithStops());
            IEnumerable<TripViewModel> results1 = _mapper.Map<IEnumerable<TripViewModel>>(_repository.GetAllUserTripsWithStops(User.Identity.Name));
            return Ok(results1);
        }



        [HttpPost("")]
        public IActionResult Post([FromBody] TripViewModel newTrip)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Trip nTrip = _mapper.Map<Trip>(newTrip);

                    //save to DB

                    //Add the trip
                    _repository.AddTrip(nTrip);

                    //If save succeeds, update the status code and send back the details
                    if (_repository.SaveAll() == true)
                    {
                        Response.StatusCode = (int)HttpStatusCode.Created;
                        return Ok(_mapper.Map<TripViewModel>(nTrip));
                    }
                }
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return BadRequest(new { Message = false, ModelError = allErrors });
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return BadRequest(new { Message = ex.Message });
            }
        }

    }
}

ASP.NetCore/Lab/07.StateMgt/Starter/GreatWorld/Controllers/Web/StopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GreatWorld.Data;
using GreatWorld.Models;

namespace GreatWorld.Controllers.Web
{
    public class StopsController : Controller
    {
        private readonly GreatWorldWithEFContext _context;

        public StopsController(GreatWorldWithEFContext context)
        {
            _context = context;
        }

        // GET: Stops
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Stops.ToListAsync());
        //}

        public async Task<IActionResult> Index(string id)
        {
            ViewBag.tripId = id;
            if (id == null)
            {
                return View(await _context.Stops.ToListAsync());
            }
            else
            {
                int tid = Convert.ToInt32(id);
                Trip trip = _context.Trips
                                    .Include(t => t.Stops)
                                    .FirstOrDefault(m => m.id == tid);
                ViewBag.TripName = trip.Name;
                List<Stop> stops = trip.Stops.ToList();
                return View(stops);
            }
        }


        // GET: Stops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stop = await _context.Stops
                .FirstOrDefaultAsync(m => m.id == id);
            if (stop == null)
            {
                return NotFound();
            }

            return View(stop);
        }

        // GET: Stops/Create
        //public IActionResult Create()
        //{
        //  return View();
        //}

        public IActionResult Create(int tripId)
        {
            Stop stop = new Stop() { Tripid = tripId };
            return View(stop);
        }

        // POST: Stops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Tripid,id,Name,Longitude,Latitude,Arrival,Order")] Stop stop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = stop.Tripid });
            }
            return View(stop);
        }

        // GET: Stops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stop = await _context.Stops.FindAsync(id);
            if (stop == null)
            {
                return NotFound();
            }
            return View(stop);
        }

        // POST: Stops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,Longitude,Latitude,Arrival,Order,Tripid")] Stop stop)
        {
            if (id != stop.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StopExists(stop.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = stop.Tripid });
            }
            return View(stop);
        }

        // GET: Stops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stop = await _context.Stops
                .FirstOrDefaultAsync(m => m.id == id);
            if (stop == null)
            {
                return NotFound();
            }

            return View(stop);
        }

        // POST: Stops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stop = await _context.Stops.FindAsync(id);
            _context.Stops.Remove(stop);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = stop.Tripid });
        }

        private bool StopExists(int id)
        {
            return _context.Stops.Any(e => e.id == id);
        }
    }
}

ASP.NetCore/Lab/07.StateMgt/Starter/GreatWorld/Controllers/Web/TripsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GreatWorld.Data;
using GreatWorld.Models;

namespace GreatWorld.Controllers.Web
{
    public class TripsController : Controller
    {
        private readonly GreatWorldWithEFContext _context;

        public TripsController(GreatWorldWithEFContext context)
        {
            _context = context;
        }

        // GET: Trips
        public async Task<IActionResult> Index()
        {
            return View(await _context.Trips.ToListAsync());
        }

        // GET: Trips/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .FirstOrDefaultAsync(m => m.id == id);
            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }

        // GET: Trips/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trips/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,Created,UserName,FullName")] Trip trip)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trip);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trip);
        }

        // GET: Trips/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips.FindAsync(id);
            if (trip == null)
            {
                return NotFound();
            }
            return View(trip);
        }

        // POST: Trips/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,Created,UserName,FullName")] Trip trip)
        {
            if (id != trip.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trip);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TripExists(trip.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trip);
        }

        // GET: Trips/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .FirstOrDefaultAsync(m => m.id == id);
            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }

        // POST: Trips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trip = await _context.Trips.FindAsync(id);
            _context.Trips.Remove(trip);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TripExists(int id)
        {
            return _context.Trips.Any(e => e.id == id);
        }
    }
}

ASP.NetCore/Lab/07.StateMgt/Starter/GreatWorld/Views/Trips/Create.cshtml
@model GreatWorld.Models.Trip

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Trip</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ASP.NetCore/Lab/07.StateMgt/Starter/GreatWorld/Views/Trips/Delete.cshtml
@model GreatWorld.Models.Trip

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trip</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASP.NetCore/Lab/07.StateMgt/Starter/GreatWorld/Views/Trips/Details.cshtml
@model GreatWorld.Models.Trip

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Trip</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ASP.NetCore/Lab/07.StateMgt/Starter/GreatWorld/Views/Trips/Edit.cshtml
@model GreatWorld.Models.Trip

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Trip</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ASP.NetCore/Lab/07.StateMgt/Starter/GreatWorld/Views/Trips/Index.cshtml
@model IEnumerable<GreatWorld.Models.Trip>

@{
    ViewData["Title"] = "Index";
}

<h1>Trips</h1>

<p>
    <a asp-action="Create" class="btn btn-success" >Create New</a>
</p>
<div class="border rounded border-success">
    <table class="table table-striped">
        <thead class="bg-primary">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FullName)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Created)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.id">Edit</a>
                        <a asp-action="Index" class="btn btn-success" asp-controller="Stops" asp-route-id="@item.id">Stops</a>
                        <a asp-action="Details" class="btn btn-info" asp-route-id="@item.id">Details</a>
                        <a asp-action="Delete" class="btn btn-danger"  asp-route-id="@item.id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>